// <auto-generated />
using System;
using Blazor_Create_Update_Delete.Shared.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BlazorCreateUpdateDelete.Server.Migrations
{
    [DbContext(typeof(TravelTourDbContext))]
    partial class TravelTourDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Blazor_Create_Update_Delete.Server.Models.DbModel+AgentTourPackage", b =>
                {
                    b.Property<int>("TravelAgentId")
                        .HasColumnType("int")
                        .HasColumnOrder(0);

                    b.Property<int>("TourPackageId")
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    b.HasKey("TravelAgentId", "TourPackageId");

                    b.HasIndex("TourPackageId");

                    b.ToTable("AgentTourPackages");
                });

            modelBuilder.Entity("Blazor_Create_Update_Delete.Server.Models.DbModel+TourPackage", b =>
                {
                    b.Property<int>("TourPackageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TourPackageId"));

                    b.Property<decimal>("CostPerPerson")
                        .HasColumnType("money");

                    b.Property<int>("PackageCategory")
                        .HasColumnType("int");

                    b.Property<string>("PackageName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("TourTime")
                        .HasColumnType("int");

                    b.HasKey("TourPackageId");

                    b.ToTable("TourPackages");
                });

            modelBuilder.Entity("Blazor_Create_Update_Delete.Server.Models.DbModel+Tourist", b =>
                {
                    b.Property<int>("TouristId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TouristId"));

                    b.Property<DateTime>("BookingDate")
                        .HasColumnType("date");

                    b.Property<int>("TourPackageId")
                        .HasColumnType("int");

                    b.Property<string>("TouristName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TouristOccupation")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TouristPicture")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TouristId");

                    b.HasIndex("TourPackageId");

                    b.ToTable("Tourists");
                });

            modelBuilder.Entity("Blazor_Create_Update_Delete.Server.Models.DbModel+TravelAgent", b =>
                {
                    b.Property<int>("TravelAgentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TravelAgentId"));

                    b.Property<string>("AgentAddress")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar(70)");

                    b.Property<string>("AgentName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("TravelAgentId");

                    b.ToTable("TravelAgents");
                });

            modelBuilder.Entity("Blazor_Create_Update_Delete.Server.Models.DbModel+AgentTourPackage", b =>
                {
                    b.HasOne("Blazor_Create_Update_Delete.Server.Models.DbModel+TourPackage", "TourPackages")
                        .WithMany("AgentTourPackages")
                        .HasForeignKey("TourPackageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Blazor_Create_Update_Delete.Server.Models.DbModel+TravelAgent", "TravelAgents")
                        .WithMany("AgentTourPackages")
                        .HasForeignKey("TravelAgentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TourPackages");

                    b.Navigation("TravelAgents");
                });

            modelBuilder.Entity("Blazor_Create_Update_Delete.Server.Models.DbModel+Tourist", b =>
                {
                    b.HasOne("Blazor_Create_Update_Delete.Server.Models.DbModel+TourPackage", "TourPackages")
                        .WithMany("Tourists")
                        .HasForeignKey("TourPackageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TourPackages");
                });

            modelBuilder.Entity("Blazor_Create_Update_Delete.Server.Models.DbModel+TourPackage", b =>
                {
                    b.Navigation("AgentTourPackages");

                    b.Navigation("Tourists");
                });

            modelBuilder.Entity("Blazor_Create_Update_Delete.Server.Models.DbModel+TravelAgent", b =>
                {
                    b.Navigation("AgentTourPackages");
                });
#pragma warning restore 612, 618
        }
    }
}
